lib/squeeze/accounts/user.ex
lib/squeeze/dashboard/dashboard.ex
lib/squeeze_web/templates/dashboard/index.html.eex
priv/repo/migrations/20171128012003_add_email_to_users.exs
test/squeeze/accounts/user_test.exs
test/squeeze/dashboard/dashboard_test.exs
test/support/factory.ex

✨ Add email to user

---

.env.example
config/config.exs
lib/squeeze/auth_error_handler.ex
lib/squeeze/guardian.ex
lib/squeeze_web/controllers/auth_controller.ex
lib/squeeze_web/controllers/page_controller.ex
lib/squeeze_web/router.ex
lib/squeeze_web/templates/dashboard/index.html.eex
mix.exs
mix.lock

🔒 Add guardian authentication

---

lib/squeeze_web/templates/shared/flash.html.eex

Fix alerts not appearing correctly

---

lib/squeeze_web/templates/wizard/personal-record.html.eex

Add skip to personal record step

---

assets/js/components/modal.js
lib/squeeze_web/templates/modal/past-due.html.eex
lib/squeeze_web/templates/overview/index.html.eex

Add trial ended modal to billing

---

lib/squeeze_web/templates/menu/_avatar.html.eex
lib/squeeze_web/templates/menu/sidebar.html.eex
lib/squeeze_web/templates/menu/topbar.html.eex

Add fallback profile picture

---

config/dev.exs
lib/squeeze/email.ex
lib/squeeze_web/controllers/user_controller.ex
lib/squeeze_web/router.ex
lib/squeeze_web/templates/email/reset_password.html.eex
lib/squeeze_web/templates/email/welcome.html.eex
lib/squeeze_web/templates/email/welcome.text.eex
lib/squeeze_web/templates/layout/email.html.eex

Add welcome email after registration

---

lib/squeeze_web/templates/overview/_workout-card.html.eex
lib/squeeze_web/views/overview_view.ex
test/squeeze_web/views/overview_view_test.exs

Calculate workout streak for overview

---

lib/squeeze_web/templates/overview/_milage-card.html.eex
lib/squeeze_web/views/overview_view.ex

Add weekly diff percentage to overview page

---

assets/js/components/activity-chart.js
assets/js/variables.js

- Add gradient line for heartrate
- Adjust min/max values for activity chart

Updates to activity chart

---

lib/squeeze_web/templates/wizard/experience.html.eex
lib/squeeze_web/views/form_helpers.ex
mix.lock

- Bug fix: app crashes when no experience level is selected (https://github.com/edance/openpace/issues/534 )
- Enhancement: Make experience step remember the selected value if user returns to the page

Enhancements and bug fixes for sign-up flow

---

lib/squeeze/accounts/user.ex
lib/squeeze/duration.ex
lib/squeeze_web/controllers/wizard_controller.ex

- Prevent divide by 0 error if user does not choose a duration

Allow user to select a value for "duration"

---

lib/squeeze_web/templates/activity/form.html.eex
lib/squeeze_web/templates/modal/_activity-form.html.eex
lib/squeeze_web/views/activity_view.ex
lib/squeeze_web/views/modal_view.ex

Add to the activity form the select dropdown for workout type.

Add UI for workout_type

---

.env.example
.gitignore
README.md
config/dev.exs
docker-compose.yml
docker/Dockerfile
docker/entrypoint.sh

This PR adds the possibility of using Docker for the development environment.
Fixes #555

Add docker config for development env

---

.env.example
config/config.exs
config/prod.exs
lib/squeeze/accounts/credential.ex
lib/squeeze/garmin/auth.ex
lib/squeeze/garmin/client.ex
lib/squeeze/garmin/middleware/oauth.ex
lib/squeeze/oauth1.ex
lib/squeeze_web/controllers/integration_controller.ex
priv/repo/migrations/20191023024347_add_token_secret_to_credentials.exs

Still a work in progress. Trying to remember OAuth 1.0 is a little trickier than I though.

Add Garmin auth integration

---

lib/squeeze_web/controllers/garmin_webhook_controller.ex
lib/squeeze_web/router.ex
lib/squeeze_web/views/garmin_webhook_view.ex
test/squeeze_web/controllers/garmin_webhook_controller_test.exs

Nothing happens currently but responds 200 with an empty json object.

Add basic webhook controller for garmin

---

lib/mix/tasks/add_slugs_to_activities.ex
lib/squeeze/challenges/challenge.ex
lib/squeeze/dashboard/activity.ex
lib/squeeze/dashboard/dashboard.ex
lib/squeeze/races/race.ex
lib/squeeze/races/race_goal.ex
lib/squeeze/repo.ex
lib/squeeze/slug_generator.ex
lib/squeeze_web/live/activity_live/index.html.heex
lib/squeeze_web/live/activity_live/show.ex
lib/squeeze_web/live/calendar_item_component.html.heex
lib/squeeze_web/live/dashboard/cards_component.html.heex
lib/squeeze_web/live/dashboard/mini_activity_card_component.html.heex
lib/squeeze_web/live/race_live/index.html.heex
lib/squeeze_web/router.ex
priv/repo/migrations/20221224224446_add_slug_to_activities.exs
test/factories/activity_factory.ex
test/squeeze/activity_matcher_test.exs
test/squeeze/dashboard/activity_test.exs
test/squeeze/dashboard/dashboard_test.exs

Add slug as an external id to activities

Add slugs to activities

---

lib/squeeze/strava/activity_loader.ex
lib/squeeze/utils.ex
test/squeeze/utils_test.exs

Additionally, handle the nil case to return nil.

Refactor laps cast to float in another function

---

lib/squeeze/races/race.ex
test/squeeze/races/races_test.exs

Race was missing the required column of slug. Added the tests as well.

Fix race goal create

---

lib/squeeze_web/controllers/strava_integration_controller.ex
test/factories/detailed_athlete_factory.ex
test/squeeze_web/controllers/strava_integration_controller_test.exs
test/support/factory.ex

Had a few errors in here recently so trying to make it a little more sturdy.

Add tests for strava integration controller

---

lib/squeeze/dashboard/dashboard.ex
lib/squeeze/distances.ex
lib/squeeze/stats.ex
lib/squeeze_web/live/trends_live/index.ex
lib/squeeze_web/live/trends_live/index.html.heex
lib/squeeze_web/router.ex
test/squeeze/stats_test.exs
test/squeeze_web/live/trends_live_test.exs

Dummy layout for now. Working on individual charts after the scaffolding is up.

Add page scaffolding for all-time and yearly trends

---

lib/squeeze/file_parser/fit_import.ex

Parses FIT files and returns metadata like distance, duration, trackpoints, and laps.

Add fit file parser

---

lib/squeeze/race_predictor.ex
test/squeeze/race_predictor_test.exs

Add tests for race_predictor as well.

Add velocity_at_vo2max_percentage to calculate vo2 based pace bands

---

lib/squeeze/dashboard/dashboard.ex
lib/squeeze/races/race_goal.ex
lib/squeeze/races/races.ex
lib/squeeze_web/live/activity_live/show.ex
lib/squeeze_web/live/dashboard/cards_component.html.heex
lib/squeeze_web/live/dashboard/overview_live.ex
lib/squeeze_web/live/race_live/index.ex
lib/squeeze_web/live/race_live/index.html.heex
lib/squeeze_web/live/race_live/new.html.heex
lib/squeeze_web/live/race_live/show.ex
lib/squeeze_web/live/race_live/show.html.heex
lib/squeeze_web/live/race_live/upcoming_races_card.ex
lib/squeeze_web/live/race_live/upcoming_races_card.html.heex
lib/squeeze_web/plugs/auth.ex
lib/squeeze_web/views/form_helpers.ex
priv/repo/migrations/20230301042552_add_activity_to_race_goals.exs
priv/repo/migrations/20230301043649_add_race_fields_to_race_goals.exs
test/factories/activity_factory.ex
test/factories/challenge_factory.ex
test/factories/detailed_activity_factory.ex
test/factories/race_goal_factory.ex
test/factories/user_factory.ex
test/squeeze/races/races_test.exs
test/squeeze_web/controllers/strava_integration_controller_test.exs
test/squeeze_web/live/overview_live_test.exs
test/squeeze_web/live/race_live_test.exs
test/support/conn_case.ex

Ideally, this makes maintaining race goals a bit easier. Adding and deleting races is for a future feature to "share a race" and get friends to race with you. That hasn't been fleshed out yet so its better to skip for now.

Add race fields to race goal

---

lib/squeeze/activities/activities.ex
lib/squeeze/activities/activity.ex
lib/squeeze/strava/activity_formatter.ex
lib/squeeze/strava/history_loader.ex
lib/squeeze/tasks/resync_strava_activities.ex
priv/repo/migrations/20241108212711_add_raw_data_to_activities.exs

This will allow me to go back and add any missing field without refetching all of the strava activities again.

Add column for raw data to activities table

---

lib/squeeze/tasks/create_trackpoint_sections.ex

Skip the trackpoint sections that have already been generated

Update trackpoint section script

---

assets/js/hooks/dashboard.js
assets/js/hooks/pace-chart.js
assets/js/hooks/weekly-activity-chart.js
lib/squeeze/activities/activities.ex
lib/squeeze/activities/activity.ex
lib/squeeze/activities/trackpoint_section.ex
lib/squeeze/races/races.ex
lib/squeeze/races/training_pace.ex
lib/squeeze/stats.ex
lib/squeeze_web/live/activity_live/show.ex
lib/squeeze_web/live/race_live/components/block.html.heex
lib/squeeze_web/live/race_live/show.ex
lib/squeeze_web/live/race_live/show.html.heex
test/squeeze/races/races_test.exs

Add pace bands chart and weekly build chart

Add charts to race#show
